# Generated by Django 4.1 on 2022-09-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_agent_agender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agender',
            field=models.CharField(default='M', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='aname',
            field=models.CharField(max_length=25, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='district',
            field=models.CharField(max_length=20, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phoneno',
            field=models.IntegerField(verbose_name='Phone No'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(max_length=20, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.IntegerField(verbose_name='Phone No'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(max_length=25, verbose_name='Name'),
        ),
    ]
