# Generated by Django 4.1 on 2022-09-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_alter_agent_agender_alter_agent_aname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Admin ID')),
                ('adname', models.CharField(max_length=25, verbose_name='Admin Name')),
                ('email', models.CharField(default='admin@gmail.com', max_length=10, verbose_name='email')),
                ('password', models.CharField(default='admin', max_length=10, verbose_name='password')),
                ('status', models.CharField(default='A', max_length=1, verbose_name='status')),
            ],
        ),
    ]
