# Generated by Django 4.1 on 2022-09-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
