# Generated by Django 4.1 on 2022-09-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_alter_agent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(default='W', max_length=2, verbose_name='User Status'),
        ),
    ]
