# Generated by Django 4.1 on 2022-09-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_alter_agent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Sample ID')),
                ('sname', models.CharField(max_length=20, verbose_name='Sample name')),
                ('password', models.CharField(max_length=20, verbose_name='passs')),
            ],
        ),
    ]
