# Generated by Django 4.1 on 2022-10-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
