# Generated by Django 4.1 on 2022-10-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_delete_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postpackage',
        ),
    ]
