# Generated by Django 4.1 on 2022-10-05 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0014_postpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestpackage',
            fields=[
                ('rqno', models.IntegerField(primary_key=True, serialize=False, verbose_name='Request No')),
                ('rqdate', models.DateField(default=datetime.date.today, verbose_name='Request Date')),
                ('uid', models.IntegerField(verbose_name='UserId')),
                ('aid', models.IntegerField(verbose_name='AgentID')),
                ('status', models.CharField(default='N', max_length=3, verbose_name='status')),
            ],
        ),
    ]
