# Generated by Django 4.1 on 2022-10-21 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0015_requestpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpackage',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent'),
        ),
        migrations.AlterField(
            model_name='requestpackage',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent'),
        ),
        migrations.AlterField(
            model_name='requestpackage',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.user'),
        ),
    ]
