# Generated by Django 4.1 on 2022-11-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0016_alter_postpackage_aid_alter_requestpackage_aid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpackage',
            name='status',
            field=models.CharField(default='POSTED', max_length=10, verbose_name='status'),
        ),
    ]
