# Generated by Django 4.1.3 on 2022-11-13 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0018_alter_postpackage_aid_alter_postpackage_aname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpackage',
            name='aid',
        ),
        migrations.RemoveField(
            model_name='postpackage',
            name='aname',
        ),
    ]
