# Generated by Django 4.1.3 on 2022-11-13 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0019_remove_postpackage_aid_remove_postpackage_aname'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpackage',
            name='aid',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, to='agent.agent'),
        ),
        migrations.AddField(
            model_name='postpackage',
            name='aname',
            field=models.CharField(default='a', max_length=26, verbose_name='Name Of Agent'),
        ),
    ]
