# Generated by Django 4.1.3 on 2022-11-13 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0020_postpackage_aid_postpackage_aname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpackage',
            name='aid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agent.agent'),
        ),
    ]
