# Generated by Django 4.1.3 on 2022-11-13 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0024_postpackage_aid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpackage',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent'),
        ),
        migrations.AlterField(
            model_name='postpackage',
            name='aname',
            field=models.CharField(max_length=26, verbose_name='Name Of Agent'),
        ),
    ]
